Repository keep-network/keep-ecdsa, pull requests merged in 2020-07, with the labels that each got.

#496 Remove BondedECDSAKeep key generation timeout
  pkg/chain/chain.go
  pkg/chain/ethereum/ethereum.go
  pkg/chain/local/local.go
  pkg/client/client.go
  pkg/node/node.go
  solidity/contracts/BondedECDSAKeep.sol
  solidity/test/BondedECDSAKeepTest.js
Labels: process & client team

#502 Migration to openzeppelin test environment
  solidity/contracts/test/BondedECDSAKeepCloneFactoryStub.sol
  solidity/contracts/test/BondedECDSAKeepFactoryStub.sol
  solidity/contracts/test/BondedECDSAKeepFactoryVendorStub.sol
  solidity/contracts/test/BondedECDSAKeepStub.sol
  solidity/contracts/test/BondedECDSAKeepVendorImplV1Stub.sol
  solidity/contracts/test/BondedECDSAKeepVendorImplV2Stub.sol
  solidity/contracts/test/ManagedGrantStub.sol
  solidity/contracts/test/RandomBeaconStub.sol
  solidity/contracts/test/TestEtherReceiver.sol
  solidity/contracts/test/TestToken.sol
  solidity/contracts/test/TokenGrantStub.sol
  solidity/contracts/test/TokenStakingStub.sol
  solidity/contracts/test/integration/ExternalContractsIntegration.sol
  solidity/package-lock.json
  solidity/package.json
  solidity/test/BondedECDSAKeepFactoryTest.js
  solidity/test/BondedECDSAKeepIntegrationTest.js
  solidity/test/BondedECDSAKeepTest.js
  solidity/test/BondedECDSAKeepVendorImplV1Test.js
  solidity/test/BondedECDSAKeepVendorImplV1viaProxyTest.js
  solidity/test/BondedECDSAKeepVendorTest.js
  solidity/test/BondedECDSAKeepVendorUpgradeTest.js
  solidity/test/KeepBondingTest.js
  solidity/test/helpers/generateTickets.js
  solidity/test/helpers/increaseTime.js
  solidity/test/helpers/listBalanceUtils.js
  solidity/test/helpers/mineBlocks.js
  solidity/test/helpers/packTicket.js
  solidity/test/helpers/snapshot.js
  solidity/test/integration/keep_signing_e2e.js
  solidity/truffle.js
Labels: ⛓chain

#509 Add 20% safety margin to sortition pool registration TX gas limit
  pkg/chain/ethereum/ethereum.go
Labels: ⛓chain

#508 Allow the application to set pool's minimum bondable value
  solidity/contracts/BondedECDSAKeepFactory.sol
  solidity/contracts/api/IBondedECDSAKeepFactory.sol
  solidity/package-lock.json
  solidity/package.json
  solidity/test-environment.config.js
  solidity/test/BondedECDSAKeepFactoryTest.js
Labels: ⛓chain

#510 Calculate the required unbonded value per keep member
  solidity/contracts/BondedECDSAKeepFactory.sol
  solidity/contracts/api/IBondedECDSAKeepFactory.sol
  solidity/test/BondedECDSAKeepFactoryTest.js
Labels: ⛓chain

#512 Firewall caching improvements
  go.mod
  go.sum
  pkg/firewall/firewall.go
  pkg/firewall/firewall_test.go
Labels: 📟 client
