Repository keep-network/keep-ecdsa, pull requests merged in 2020-08, with the labels that each got.

#523 Consult authorization caches before hitting ETH client
  pkg/firewall/firewall.go
  pkg/firewall/firewall_test.go
Labels: process & client team, 📟 client

#529 Extract generic keep factory code from Bonded ECDSA Keep Factory
  solidity/contracts/BondedECDSAKeepFactory.sol
  solidity/contracts/CandidatesPools.sol
  solidity/contracts/GroupSelectionSeed.sol
  solidity/contracts/KeepCreator.sol
Labels: ⛓chain

#530 Extracted parts of ECDSA keep from Bonded ECDSA Keep
  solidity/contracts/AbstractBondedECDSAKeep.sol
  solidity/contracts/AbstractBonding.sol
  solidity/contracts/BondedECDSAKeep.sol
  solidity/contracts/api/IBondingManagement.sol
Labels: ⛓chain

#532 Add GoSec workflow
  .github/workflows/gosec.yml
  .gitignore
  go.mod
  go.sum
  internal/config/config.go
  internal/testdata/tss.go
  pkg/chain/chain.go
  pkg/chain/ethereum/ethereum.go
  pkg/chain/gen/cmd/BondedECDSAKeep.go
  pkg/chain/gen/cmd/BondedECDSAKeepFactory.go
  pkg/chain/gen/cmd/BondedECDSAKeepVendor.go
  pkg/chain/gen/contract/BondedECDSAKeep.go
  pkg/chain/gen/contract/BondedECDSAKeepFactory.go
  pkg/chain/gen/contract/BondedECDSAKeepVendor.go
  pkg/chain/local/local.go
  pkg/chain/local/local_test.go
  pkg/client/client.go
  pkg/ecdsa/tss/gen/pb/message.pb.go
  pkg/ecdsa/tss/gen/pb/signer.pb.go
  pkg/ecdsa/tss/message.go
  pkg/ecdsa/tss/network.go
  pkg/ecdsa/tss/protocol_announce_test.go
  pkg/ecdsa/tss/protocol_ready_test.go
Labels: process & client team, 📟 client

#533 Crytic setup and basic improvements
  crytic-config.json
  solidity/contracts/AbstractBondedECDSAKeep.sol
  solidity/contracts/BondedECDSAKeepFactory.sol
  solidity/contracts/BondedECDSAKeepVendor.sol
  solidity/contracts/GroupSelectionSeed.sol
  solidity/contracts/test/BondedECDSAKeepVendorImplV2Stub.sol
  solidity/contracts/test/RandomBeaconStub.sol
  solidity/package-lock.json
  solidity/package.json
  solidity/slither.config.json
Labels: process & client team
