Repository keep-network/keep-ecdsa, pull requests merged in 2020-04, with the labels that each got.

#346 Concurrent handling of BondedECDSAKeepCreated event
  pkg/client/client.go
Labels: 📟 client

#344 Circle Migrations: Don't fail if Tenderly fails
  solidity/scripts/circleci-migrate-contracts.sh
Labels: :cloud: infrastructure

#375 Remove redundant tests
  solidity/test/BondedECDSAKeepFactoryTest.js
Labels: ⛓chain

#377 Minimum stake schedule
  solidity/contracts/BondedECDSAKeepFactory.sol
  solidity/package-lock.json
  solidity/package.json
  solidity/test/BondedECDSAKeepFactoryTest.js
  solidity/test/BondedECDSAKeepIntegrationTest.js
  solidity/test/contracts/TokenStakingStub.sol
Labels: ⛓chain

#416 Do not revert signature fraud submission TX if slashing failed
  solidity/contracts/BondedECDSAKeep.sol
  solidity/test/BondedECDSAKeepTest.js
  solidity/test/contracts/BondedECDSAKeepStub.sol
  solidity/test/contracts/TokenStakingStub.sol
Labels: ⛓chain

#406 Minimum stake or active keep membership firewall policy
  cmd/start.go
  go.mod
  go.sum
  pkg/chain/chain.go
  pkg/chain/ethereum/ethereum.go
  pkg/chain/local/bonded_ecdsa_keep.go
  pkg/chain/local/local.go
  pkg/firewall/cache.go
  pkg/firewall/cache_test.go
  pkg/firewall/firewall.go
  pkg/firewall/firewall_test.go
  solidity/contracts/BondedECDSAKeepFactory.sol
  solidity/test/BondedECDSAKeepFactoryTest.js
Labels: 📟 client

#426 Use cache from keep-common, sweep old entries before looking into the cache
  go.mod
  go.sum
  pkg/firewall/cache.go
  pkg/firewall/cache_test.go
  pkg/firewall/firewall.go
  pkg/firewall/firewall_test.go
Labels: 📟 client
