Repository keep-network/keep-ecdsa, pull requests merged in 2020-10, with the labels that each got.

#564 Improvements of the storage layer
  cmd/signing.go
  go.mod
  go.sum
  pkg/client/client.go
  pkg/node/node.go
  pkg/registry/keeps.go
  pkg/registry/keeps_test.go
  pkg/registry/registry.go
  pkg/registry/storage.go
Labels: 📟 client

#567 Backer ECDSA rewards
  solidity/contracts/ECDSABackportRewards.sol
  solidity/contracts/test/BondedECDSAKeepFactoryStub.sol
  solidity/package-lock.json
  solidity/package.json
  solidity/test/rewards/TestECDSABackportRewards.js
Labels: ⛓chain

#581 Fixing tests when future intervals are over
  solidity/contracts/test/BondedECDSAKeepFactoryStub.sol
  solidity/test/rewards/TestECDSARewards.js
Labels: ⛓chain

#579 Allowing stakers to receive rewards for multiple keeps
  solidity/contracts/ECDSARewards.sol
  solidity/contracts/test/BondedECDSAKeepFactoryStub.sol
  solidity/test/rewards/TestECDSARewards.js
Labels: ⛓chain

#582 More ECDSA mainnet bootstraps
  docs/run-keep-ecdsa.adoc
Labels: :book: documentation

#580 Initial implementation of app-specific actions
  cmd/start.go
  configs/config.toml.SAMPLE
  go.mod
  go.sum
  internal/config/config.go
  pkg/chain/ethereum/connect.go
  pkg/chain/ethereum/tbtc.go
  pkg/chain/local/bonded_ecdsa_keep.go
  pkg/chain/local/bonded_ecdsa_keep_factory.go
  pkg/chain/local/local.go
  pkg/chain/local/tbtc.go
  pkg/extensions/tbtc/chain.go
  pkg/extensions/tbtc/tbtc.go
  pkg/extensions/tbtc/tbtc_test.go
Labels: 📟 client

#586 Added Staked ECDSA mainnet bootstrap nodes
  docs/run-keep-ecdsa.adoc
Labels: :book: documentation

#584 Cap the maximum reward per ECDSA keep operator per interval
  solidity/contracts/ECDSARewards.sol
  solidity/package-lock.json
  solidity/package.json
  solidity/test/rewards/TestECDSARewards.js
Labels: ⛓chain

#587 Rewards cap tests
  solidity/contracts/ECDSARewards.sol
  solidity/contracts/test/ECDSARewardsStub.sol
  solidity/test/rewards/TestECDSARewards.js
Labels: ⛓chain
